### ISSUE TITLE
Замечания 🐱‍💻

### ISSUE THREAD

**Issue by Fasturtle1** [NikitaStromenko/Vue_2.0#1]
- [x] Не работает поиск по сотрудникам (нет параметра v-model)  
 - [x] Чекбоксы в колонке "Почасовая" выровнять по центру  
 - [x] Чекбокс "Не показывать уволенных" центрировать относительно соседней кнопки  
 - [x]  При нажатии на элемент колонки "Ставка", "База" и "Аванс" заполнять диалоги данными из таблицы  
![image](https://user-images.githubusercontent.com/35260551/60663748-a1764b00-9e4f-11e9-93d6-2921818a8f16.png)  
- [x] При добавлении сотрудника заменить поле "Дата приёма" на vuetify-компонент v-date-picker  
- [x]  Исправить формат дат в таблице. Пример:  
![image](https://user-images.githubusercontent.com/35260551/60664172-bbfcf400-9e50-11e9-850c-88f87a6016d1.png)

**Comment by Fasturtle1** [comment]
По поводу пункта *Чекбокс "Не показывать уволенных" центрировать относительно соседней кнопки*:  
Примерно так   
![image](https://user-images.githubusercontent.com/35260551/60710233-bdd2c000-9f01-11e9-991a-92cb43f35c12.png)

**Comment by NikitaStromenko** [comment]
Готово

**Comment by Fasturtle1** [comment]
Отлично!
